server:
  port: 8080
logging:
  level:
    root: INFO
    com.huawei: DEBUG
zuul:   
  routes:   
    user-service: #让zuul方向代理微服务，路径是/user-path  abc只要是唯一的就行，可随意写  
      path: /user/**  #封层匹配
      serviceId: ecommerce-user-service
    product-service:
      path: /product/**
      serviceId: ecommerce-product-service
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
  eureka:  
    enabled: false

ecommerce-user-service: #这是Ribbon要请求的微服务的ServiceId  
  ribbon:  
    listOfServers: localhost:8081

ecommerce-product-service:
  ribbon:
    listOfServers: localhost:8082
